name: ${project.name}
main: io.github.archemedes.betterbooks.BetterBooks
version: ${project.version}
description: ${project.description}
depend: [ArcheCore, CustomItem]
softdepend: [Multiworld, Multiverse-Core]

commands:
  signbook:
    description: Changes the author of a written book
    usage: /signbook [author name]
  fixbook:
    description: Fixes missing texture books.
    usage: /fixbook

  