name: BetterBooks
main: io.github.archemedes.betterbooks.BetterBooks
version: 1.35
depend: [ArcheCore, Customizer]
softdepend: [Multiworld, Multiverse-Core]

commands:
  signbook:
    description: Changes the author of a written book
    usage: /signbook [author name]
  fixbook:
    description: Fixes missing texture books.
    usage: /fixbook

  